# Generated by Django 5.1.7 on 2025-03-17 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genres_club_host_club_rules_club_genres_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='club',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='club',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
