# Generated by Django 5.1.7 on 2025-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options_club_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='participant',
            new_name='participants',
        ),
    ]
