# Generated by Django 5.1.7 on 2025-03-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_create_room_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='create',
            new_name='created',
        ),
    ]
